<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Reply extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'ticket_id',
        'user_id', // Nullable: can be null if reply is from AI/system
        'content',
        'is_ai_reply', // Boolean: true if reply is generated by AI
        'reply_from_source', // e.g., 'system_panel', 'ai_service', 'customer_web'
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'is_ai_reply' => 'boolean',
    ];

    /**
     * Get the ticket that the reply belongs to.
     */
    public function ticket(): BelongsTo
    {
        return $this->belongsTo(Ticket::class);
    }

    /**
     * Get the user that made the reply (if any).
     */
    public function user(): BelongsTo
    {
        // user_id can be null (e.g., AI reply)
        return $this->belongsTo(User::class, 'user_id')->withDefault([
            'name' => 'AI/System',
            'email' => 'system@example.com'
        ]);
    }
}
